config/routes.rb
Rubly::Application.routes.draw do
  resources :views

  resources :links

  match ':slug' => 'links#render_link'

   root :to => "links#new"

end

app/models/link.rb
class Link < ActiveRecord::Base

  has_many :views

  validates_presence_of :long_url, :ip_address
  validates_uniqueness_of :long_url, :short_url
  validates_format_of :long_url, :with => /^(http):\/\/[a-z0-9]/ix, :on => :save, :message => 'Invalid url'

  before_create :generate_short_url



  def get_link_by_slug(slug)
    Link.find_by_slug(slug)
  end

  def update_views(request)

    view = views.build(:ip_address => request.remote_ip, :referer => request.referer,
                       :browser => request.user_agent)
    view.save

  end


  private

    def generate_short_url
      generate_slug
      self.short_url = BASE_URL + self.slug
    end

   def generate_slug
       slug_string = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-'
       slug = ''
       5.times do
         index = rand(slug_string.length);
         slug += slug_string[index..index]
       end
       if is_slug_available(slug)
          generate_slug
       end
       self.slug = slug
   end

   def is_slug_available(slug)
       @link = Link.find_by_slug(slug)
       if @link.nil?
         return false
       else
         return true
       end
   end


end

app/models/view.rb
class View < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def init_layout_data
    @links = Link.all;
  end
  def page_title
    "Rubly- Url Shortener"
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  before_filter :init_layout_data
  def index
   redirect_to '/links/new'
   return
  end


  def show
    @link = Link.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @link }
    end
  end


  def new
    @link = Link.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @link }
    end
  end


  def create
    @link = Link.new(params[:link])
    @link.ip_address = request.remote_ip
    respond_to do |format|
      if @link.save
        format.html { redirect_to('/', :notice => 'Link was successfully created.') }
        format.xml  { render :xml => @link, :status => :created, :location => @link }
        format.js
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @link.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  def render_link

    slug = params[:slug]
    @link = Link.new
    @link = @link.get_link_by_slug(slug)
     respond_to do |format|
      if @link.nil?
        format.html {redirect_to(@link, :notice => 'Invalid Link')}
      else

        @link.update_views(request)
        format.html {redirect_to(@link.long_url, :status => 301)}
      end
     end

  end

end

app/controllers/views_controller.rb
class ViewsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/views_helper.rb
module ViewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title><%= controller.page_title %></title>
  <meta name="description" content="Rubly URL Shortener is used to create short URLs that can be easily shared, tweeted, or emailed to friends.">
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag "bootstrap", "rubly" %>
  <%= javascript_include_tag "jquery.min", "jquery-ui.min", "application" %>
  <%= csrf_meta_tag %>

  <link rel="shortcut icon" href="../images/favicon.ico">
  <link rel="apple-touch-icon" href="../images/apple-touch-icon.png">
  <link rel="apple-touch-icon" sizes="72x72" href="../images/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="../images/apple-touch-icon-114x114.png">
  <style type="text/css">
      body {
        padding-top: 60px;
      }
  </style>
</head>
<body>

<div class="topbar">
  <div class="fill">
    <div class="container">
      <a class="brand" href="#">Rubly url shortener</a>
      <ul class="nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
    </div>
  </div>
</div>

<div class="container">
   <div class="hero-unit">
        <%= yield %>
   </div>
   <%= render 'links' %>
  <footer>
    <p>&copy; rbs 2011</p>
  </footer>

</div>
<!-- /container -->

</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :long_url %><br />
    <%= f.text_field :long_url %>
  </div>
  <div class="field">
    <%= f.label :short_url %><br />
    <%= f.text_field :short_url %>
  </div>
  <div class="field">
    <%= f.label :ip_address %><br />
    <%= f.text_field :ip_address %>
  </div>
  <div class="field">
    <%= f.label :total_click %><br />
    <%= f.text_field :total_click %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/_link.html.erb
<tr>
  <td><%= @link.long_url %></td>
  <td><%= @link.short_url %></td>
  <td><%= @link.ip_address %></td>
  <td><%= @link.total_click %></td>
  <td><%= link_to 'Details', @link, :class => "btn primary" %></td>
</tr>

app/views/links/_links.html.erb
<div class="row">
  <div class="span16">
    <table class="zebra-striped" id="links">
      <thead>
      <tr>
        <th width="55%">Long url</th>
        <th width="20%">Short url</th>
        <th width="10%">Ip address</th>
        <th width="5%">Clicks</th>
        <th width="10%"></th>

      </tr>
      </thead>
      <tbody>
      <% @links.each do |link| %>
          <tr>
            <td><%= link.long_url %></td>
            <td><%= link.short_url %></td>
            <td><%= link.ip_address %></td>
            <td><%= link.total_click %></td>
            <td><%= link_to 'Details', link, :class => "btn primary" %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/links/_message.html.erb
<% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<div class="row">
  <div class="span16">
    <table>
      <thead>
      <tr>
        <th>Long url</th>
        <th>Short url</th>
        <th>Ip address</th>
        <th>Total click</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @links.each do |link| %>
          <tr>
            <td><%= link.long_url %></td>
            <td><%= link.short_url %></td>
            <td><%= link.ip_address %></td>
            <td><%= link.total_click %></td>
            <td><%= link_to 'Show', link %></td>
            <td><%= link_to 'Edit', edit_link_path(link) %></td>
            <td><%= link_to 'Destroy', link, :confirm => 'Are you sure?', :method => :delete %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/links/new.html.erb
<div class="row">
    <div class="span10" id="message-container">

    </div>
</div>
<div class="row">
  <div class="span10">
    <%= form_for @link, :html => {:class => "form-stacked"} do |form| %>
        <%= render 'message' %>

        <div class="clearfix">
          <%= label_tag(:long_url, "Please Paste the long Url here") %>
          <div class="input">
            <%= form.text_field :long_url, :size => '30', :class => 'span8' %>
            <span class="help-inline">
              <%= form.submit "Shorten", :class => "btn primary" %>
            </span>
            <span class="help-block">
              All rub.ly URLs and click analytics are public and can be shared by anyone.
            </span>

          </div>
        </div>
    <% end %>
  </div>
  <div class="span3">
      <div class="clearfix">

       <div class="input">
          <label>&nbsp;</label>
          <input type="text" size="10" name="result" id="result" class="span3" readonly="" value="http://rub.ly/...">
        </div>
      </div>
  </div>
</div>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>Here is your short url. Just copy and paste the url to share</p>
<p>
  <b>Shore url:</b>
  <div class="selected">
      <input type="text" readonly="" value="<%= @link.short_url %>" id="result">
  </div>
</p>

<%= link_to 'Back', links_path %>

app/views/views/_form.html.erb
<%= form_for(@view) do |f| %>
  <% if @view.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@view.errors.count, "error") %> prohibited this view from being saved:</h2>

      <ul>
      <% @view.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :references %><br />
    <%= f.text_field :references %>
  </div>
  <div class="field">
    <%= f.label :ip_address %><br />
    <%= f.text_field :ip_address %>
  </div>
  <div class="field">
    <%= f.label :browser %><br />
    <%= f.text_field :browser %>
  </div>
  <div class="field">
    <%= f.label :referer %><br />
    <%= f.text_field :referer %>
  </div>
  <div class="field">
    <%= f.label :platform %><br />
    <%= f.text_field :platform %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/views/edit.html.erb
<h1>Editing view</h1>

<%= render 'form' %>

<%= link_to 'Show', @view %> |
<%= link_to 'Back', views_path %>

app/views/views/index.html.erb
<h1>Listing views</h1>

<table>
  <tr>
    <th>References</th>
    <th>Ip address</th>
    <th>Browser</th>
    <th>Referer</th>
    <th>Platform</th>
    <th>Country</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @views.each do |view| %>
  <tr>
    <td><%= view.references %></td>
    <td><%= view.ip_address %></td>
    <td><%= view.browser %></td>
    <td><%= view.referer %></td>
    <td><%= view.platform %></td>
    <td><%= view.country %></td>
    <td><%= link_to 'Show', view %></td>
    <td><%= link_to 'Edit', edit_view_path(view) %></td>
    <td><%= link_to 'Destroy', view, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New View', new_view_path %>

app/views/views/new.html.erb
<%= form_for @link  do |form|%>


<% end %>

app/views/views/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>References:</b>
  <%= @view.references %>
</p>

<p>
  <b>Ip address:</b>
  <%= @view.ip_address %>
</p>

<p>
  <b>Browser:</b>
  <%= @view.browser %>
</p>

<p>
  <b>Referer:</b>
  <%= @view.referer %>
</p>

<p>
  <b>Platform:</b>
  <%= @view.platform %>
</p>

<p>
  <b>Country:</b>
  <%= @view.country %>
</p>


<%= link_to 'Edit', edit_view_path(@view) %> |
<%= link_to 'Back', views_path %>